name: Create Catalog-info.yaml

on:
  pull_request:
    branches: [main]
    paths:
      - 'catalog-info.yaml'
      - '.github/workflows/catalog.yaml'
    # You can even set it to run only when TechDocs related files are updated.


jobs:
  create-backstage-config-file:
    runs-on: ubuntu-latest
    outputs:
      deploy-status: ${{ steps.check_changes.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: backstage-test-kim/red-team-repo
          path: red-team-repo
          submodules: 'false'
    
           
      - name: generate catalog-info.yaml
        uses: kim5566/catalog-generate-action@main
        with:
          config_file: '{"Name":"Orange","Team":"orange","Lifecycle":"production","Type":"website","ProvidesApis":[{"Name":"API2", "Type":"grpc","Lifecycle":"experimental","Definition":"https://github.com/backstage-test-kim/test-action-mkdocs/blob/master/test.proto"}]}'

      - run: cat catalog-info.yaml


      - run: cat catalog-info.yaml
    
      - name: Check diff
        shell: bash
        run: |
          rm -rf red-team-repo
          if [ -z "$(git diff --exit-code)" -a -z "$(git ls-files -o --exclude-standard)" ]
          then
            echo "nothing to commit. skip pr"
            touch skip-pr
          else
            echo "catalog-info.yaml" updated
            git add catalog-info.yaml
          fi
          
      - name: Create Pull Request
        if: hashFiles('skip-pr') == ''
        uses: peter-evans/create-pull-request@v3
        with:
          title: Auto-update Backstage catalog-info.yaml configuration
          commit-message: 'auto-update Backstage catalog-info.yaml configuration'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            # Origin Details
            **Message**: ${{ github.event.head_commit.message }}
          branch: feature/update-backstage
          labels: |
             backstage
             autogenerated

