name: Create Catalog-info.yaml

on:
  push:
    branches: [main]
    # You can even set it to run only when TechDocs related files are updated.
    # paths:
    #   - "docs/**"
    #   - "mkdocs.yml"

jobs:
  create-backstage-config-file:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.pull_request.head.ref }}
      - run: cat test.json 

      - name: generate catalog-info.yaml
        uses: kim5566/catalog-generate-action@main
        with:
          config_file: |-
            ```
            {
             "name": "Orange Team",
              "team": "Tets",
              "lifecycle": "production",
              "description": "test",
              "providesApis": [
                {
                  "name": "api1",
                  "definition": "https://github.com/aystzh/go-modules/blob/master/protobuf/simple_service.proto",
                  "type": "grpc",
                  "lifecycle": "production"
                },
               {
                  "name": "api2",
                  "definition": "https://github.com/aystzh/go-modules/blob/master/protobuf/simple_service.proto",
                  "type": "grpc",
                  "lifecycle": "experimental"
                }
               ]
              }
              ```
      - run: cat catalog-info.yaml
    
      - name: Check for changes
        id: check_changes
        run: |
          echo "::set-output name=changes::$(git status --porcelain)"
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes != ''
        uses: peter-evans/create-pull-request@v3
        with:
          title: Auto-update Backstage catalog-info.yaml configuration
          commit-message: 'auto-update Backstage catalog-info.yaml configuration'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            # Origin Details
            **Author**: ${{ github.actor }}
            **Commit**: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            **Message**: ${{ github.event.head_commit.message }}
