name: Create Catalog-info.yaml

on:
  push:
    branches: [main]
    # You can even set it to run only when TechDocs related files are updated.


jobs:
  create-backstage-config-file:
    runs-on: ubuntu-latest
    outputs:
      deploy-status: ${{ steps.check_changes.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: backstage-test-kim/red-team-repo
          path: red-team-repo
          submodules: 'false'
    
           
      - name: generate catalog-info.yaml
        uses: kim5566/catalog-generate-action@main
        with:
          config_file: '{"Name":"Orange","Team":"orange","Lifecycle":"production","Type":"website","ProvidesApis":[{"Name":"API2", "Type":"grpc","Lifecycle":"experimental","Definition":"https://github.com/backstage-test-kim/test-action-mkdocs/blob/master/test.proto"}]}'
      - run: cat catalog-info.yaml
    
      - name: Check for changes
        id: check_changes
        run: |
          echo "::set-output name=changes::$(git status --porcelain)"
          

             
  after-deploy:
    runs-on: ubuntu-latest
    needs: [create-backstage-config-file]
    if: needs.create-backstage-config-file.outputs.deploy-status != ''
    steps:
          
      - name: Commit 
        if: steps.check_changes.outputs.changes != ''
        run: |
           git config --global user.name ${{ github.actor }}
           git config --global user.email 'kimj5566@users.noreply.github.com'
           rm -rf red-team-repo
           git add catalog-info.yaml
           git commit -m"test"
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes != ''
        uses: peter-evans/create-pull-request@v3
        with:
          title: Auto-update Backstage catalog-info.yaml configuration
          commit-message: 'auto-update Backstage catalog-info.yaml configuration'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            # Origin Details
            **Message**: ${{ github.event.head_commit.message }}
          branch: feature/update-backstage
          labels: |
             backstage
             autogenerated
