name: Create Catalog-info.yaml

on:
  push:
    branches: [main]
    # You can even set it to run only when TechDocs related files are updated.
    # paths:
    #   - "docs/**"
    #   - "mkdocs.yml"

jobs:
  create-backstage-config-file:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - run: cat test.json 

      - name: generate catalog-info.yaml
        uses: kim5566/catalog-generate-action@main
        with:
          config_file: ${{ github.workspace }}/test.json

      - run: cat catalog-info.yaml
    
      - id: check_changes
        run: echo "::set-output name=changes::$(git status --procelain)"
      
      - if: steps.check_changes != ''
        run: |
          {
            git config --global user.email "kim0471@hotmail.com" &&
            git config --global user.name "kim"&&
            git add catalog-info.yaml&&
            git commit -m"test"&&
            git push --setupstream origin ${{ github.event.pull_request.head.ref }}
          } 